vich_uploader:
    db_driver: orm

    mappings:
        image_projet:
            uri_prefix: /images/projet
            upload_destination: '%kernel.project_dir%/public/img/uploads'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
